#:schema node_modules/wrangler/config-schema.json
name = "lowkey-photo-list-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
routes = [
	{ pattern = "lowkeyphotos.com/list-photos", zone_name = "lowkeyphotos.com" },
]

[observability]
enabled = true

[placement]
mode = "smart"

[[r2_buckets]]
binding = "lowkey_photos_bucket"
bucket_name = "lowkey"
